In [1]:
import numpy as np
from transformation import *
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D 

In [20]:
zAxis = np.array([1, -np.sqrt(2)/2, np.sqrt(2)/2])
xAxis = np.array([1,0,0])
P = pointing_matrix(xAxis,zAxis)
xAxis_normalized, yAxis_normalized, zAxis_normalized = P[0,:], P[1,:], P[2,:]
# components of antenna axes in horizontal coordinate system
yAxis_normalized


yAxis = np.cross(zAxis,xAxis)
yAxis_normalized = yAxis/np.linalg.norm(yAxis)
zAxis_normalized = zAxis/np.linalg.norm(zAxis)
xAxis_normalized = np.cross(yAxis_normalized,zAxis_normalized)

In [26]:
def func(lst):
    lat = 1.5
    rot = rotation_matrix_local2eq(lst, lat)[0]
    zAxis_eq_car = np.einsum('ij,j -> i',rot, zAxis_normalized)
    xAxis_eq_car = np.einsum('ij,j -> i',rot, xAxis_normalized)
    yAxis_eq_car = np.einsum('ij,j -> i',rot, yAxis_normalized)
    theta_phi = coordinate_mapping_car2sph(zAxis_eq_car)
    rot_2 = rotation_matrix_car2sph(theta_phi)
    zAxis_eq_sph = np.einsum('ij,j -> i',rot_2, zAxis_eq_car)
    xAxis_eq_sph = np.einsum('ij,j -> i',rot_2, xAxis_eq_car)
    yAxis_eq_sph = np.einsum('ij,j -> i',rot_2, yAxis_eq_car)
    return xAxis_eq_sph, yAxis_eq_sph

In [27]:
func(200000)

(array([-5.55111512e-17,  6.14060523e-01,  7.89258940e-01]),
 array([ 2.77555756e-17, -7.89258940e-01,  6.14060523e-01]))

array([1.45444104, 0.57079633])

In [12]:
lst = 200000
lat = 1
rot = rotation_matrix_local2eq(lst, lat)[0]
zAxis_eq_car = np.einsum('ij,j -> i',rot, zAxis_normalized)
xAxis_eq_car = np.einsum('ij,j -> i',rot, xAxis_normalized)
yAxis_eq_car = np.einsum('ij,j -> i',rot, yAxis_normalized)
theta_phi = coordinate_mapping_car2sph(zAxis_eq_car)
rot_2 = rotation_matrix_car2sph(theta_phi)
zAxis_eq_sph = np.einsum('ij,j -> i',rot_2, zAxis_eq_car)
xAxis_eq_sph = np.einsum('ij,j -> i',rot_2, xAxis_eq_car)
yAxis_eq_sph = np.einsum('ij,j -> i',rot_2, yAxis_eq_car)

In [13]:
theta_hat_eq = np.array([np.cos(theta)*np.cos(phi), np.cos(theta)*np.sin(phi), -np.sin(theta)])
phi_hat_eq = np.array([-np.sin(phi), np.cos(phi), 0])
theta_hat_local = rotation_matrix_eq2local(lst, lat)[0]@theta_hat_eq
phi_hat_local = rotation_matrix_eq2local(lst, lat)[0]@phi_hat_eq

NameError: name 'theta' is not defined

In [9]:
rot

array([[ 0.09768882,  0.83578126, -0.54030231],
       [-0.99323836,  0.11609291,  0.        ],
       [ 0.06272527,  0.53664897,  0.84147098]])

In [10]:
zAxis_eq_car

array([-0.54030231,  0.        ,  0.84147098])

In [11]:
rot_2

array([[-5.40302306e-01, -8.41470985e-01, -1.22464680e-16],
       [ 6.61679489e-17,  1.03050475e-16, -1.00000000e+00],
       [ 8.41470985e-01, -5.40302306e-01,  0.00000000e+00]])

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
#x,y,z = theta_hat_local
#ax.quiver(0,0,0,x,y,z)
x,y,z = phi_hat_local
ax.quiver(0,0,0,x,y,z,headwidth=0, headlength=0, headaxislength=0)
plt.show()

In [ ]:
phi_hat_local

In [ ]:
theta_hat_eq

In [ ]:
rotation_matrix_eq2local(lst, lat)